import { ProfessionalProfile, Review } from "@/types";

export const MOCK_PROFESSIONALS: ProfessionalProfile[] = [
  {
    id: "prof-1",
    name: "Jaqueline Silva",
    email: "jaque@example.com",
    role: "PROFESSIONAL",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jaque",
    phone: "(11) 98765-4321",
    rating: 4.9,
    totalServices: 124,
    bio: "Especialista em limpezas detalhadas e organização de closets. Trabalho com dedicação e respeito ao seu lar há mais de 10 anos.",
    specialties: ["Limpeza Pesada", "Organização", "Pós-obra"],
    basePricePerHour: 35,
    completedJobs: 150,
    joinedAt: "2022-01-15",
    location: "Pinheiros, São Paulo",
  },
  {
    id: "prof-2",
    name: "Maria Oliveira",
    email: "maria@example.com",
    role: "PROFESSIONAL",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    phone: "(11) 91234-5678",
    rating: 4.8,
    totalServices: 89,
    bio: "Adoro animais e sou especialista em casas com pets. Faço uma limpeza ágil e eficiente.",
    specialties: ["Limpeza Leve", "Passar Roupa", "Cozinhar"],
    basePricePerHour: 30,
    completedJobs: 95,
    joinedAt: "2023-03-10",
    location: "Vila Mariana, São Paulo",
  },
  {
    id: "prof-3",
    name: "Luciana Santos",
    email: "lu@example.com",
    role: "PROFESSIONAL",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Luciana",
    phone: "(11) 97777-8888",
    rating: 5.0,
    totalServices: 45,
    bio: "Perfeccionista e pontual. Minha meta é deixar sua casa brilhando e com cheirinho de limpeza.",
    specialties: ["Limpeza Pesada", "Lavar Roupa"],
    basePricePerHour: 40,
    completedJobs: 48,
    joinedAt: "2024-02-20",
    location: "Itaim Bibi, São Paulo",
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    serviceId: "srv-1",
    fromId: "client-1",
    toId: "prof-1",
    rating: 5,
    comment: "A Jaque é maravilhosa! Muito educada e deixou tudo impecável.",
    createdAt: "2024-05-10T14:00:00Z",
  },
  {
    id: "rev-2",
    serviceId: "srv-2",
    fromId: "client-2",
    toId: "prof-2",
    rating: 4,
    comment: "Muito boa profissional, chegou no horário e foi muito atenciosa.",
    createdAt: "2024-05-12T10:00:00Z",
  },
];
